#!/usr/bin/env python3
"""Generate splash + error framebuffers as C arrays for firmware embedding."""
import sys, os
from pathlib import Path

HERE = Path(__file__).parent.parent
sys.path.insert(0, str(HERE / "server"))
from renderer import render_dashboard_raw, render_dashboard_raw_bw

OUT = HERE / "firmware" / "src" / "embedded_screens.h"

lines = []
lines.append("// Auto-generated splash + error screens for E1001/E1002")
lines.append("// Generated by scripts/generate_embedded_screens.py")
lines.append("#pragma once")
lines.append('#include <cstdint>')
lines.append("")

# ── E1002 (7-color, nibble-packed 800*480/2 = 192000 bytes) ──
for name, ctx, var in [
    ("splash.html", {"device": "E1002"}, "splash_e1002"),
    ("error.html", {"message": "WiFi connection failed."}, "error_wifi_e1002"),
    ("error.html", {"message": "Failed to fetch dashboard."}, "error_fetch_e1002"),
]:
    raw = render_dashboard_raw(name, ctx)
    lines.append(f"// {var}: {name} ({len(raw)} bytes)")
    lines.append(f"const uint8_t {var}[] PROGMEM = {{")
    for i in range(0, len(raw), 12):
        chunk = raw[i:i+12]
        hexes = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"  {hexes},")
    lines.append("};")
    lines.append(f"const size_t {var}_len = {len(raw)};")
    lines.append("")

# ── E1001 (monochrome, bit-packed 800*480/8 = 48000 bytes) ──
for name, ctx, var in [
    ("splash.html", {"device": "E1001"}, "splash_e1001"),
    ("error.html", {"message": "WiFi connection failed."}, "error_wifi_e1001"),
    ("error.html", {"message": "Failed to fetch dashboard."}, "error_fetch_e1001"),
]:
    raw = render_dashboard_raw_bw(name, ctx)
    lines.append(f"// {var}_bw: {name} ({len(raw)} bytes)")
    lines.append(f"const uint8_t {var}_bw[] PROGMEM = {{")
    for i in range(0, len(raw), 12):
        chunk = raw[i:i+12]
        hexes = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"  {hexes},")
    lines.append("};")
    lines.append(f"const size_t {var}_bw_len = {len(raw)};")
    lines.append("")

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(lines) + "\n")
print(f"Wrote {OUT} ({OUT.stat().st_size} bytes)")
