[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio
board_build.psram_type = opi
board_build.arduino.psram_fix = enable
build_flags =
    -DCONFIG_BT_NIMBLE_MEM_ALLOC_MODE_EXTERNAL=1
    -DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
    -DCONFIG_BT_NIMBLE_MSYS1_BLOCK_COUNT=4
    -DCONFIG_BT_NIMBLE_TRANSPORT_ACL_FROM_LL_COUNT=4
    -DCONFIG_BT_NIMBLE_ROLE_CENTRAL_DISABLED
    -DCONFIG_BT_NIMBLE_ROLE_OBSERVER_DISABLED
    -D E1002_VARIANT
    -include src/SdkConfigOverride.h
lib_deps =
    zinggjm/GxEPD2 @ 1.6.9
    adafruit/Adafruit GFX Library
    h2zero/NimBLE-Arduino

[env:reterminal_e1001]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio
board_build.psram_type = opi
board_build.arduino.psram_fix = enable
build_flags =
    -DCONFIG_BT_NIMBLE_MEM_ALLOC_MODE_EXTERNAL=1
    -DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
    -DCONFIG_BT_NIMBLE_MSYS1_BLOCK_COUNT=4
    -DCONFIG_BT_NIMBLE_TRANSPORT_ACL_FROM_LL_COUNT=4
    -DCONFIG_BT_NIMBLE_ROLE_CENTRAL_DISABLED
    -DCONFIG_BT_NIMBLE_ROLE_OBSERVER_DISABLED
    -D E1001_VARIANT
    -include src/SdkConfigOverride.h
lib_deps =
    zinggjm/GxEPD2 @ 1.6.9
    adafruit/Adafruit GFX Library
    h2zero/NimBLE-Arduino
